server:
  port: 9001

spring:
  profiles:
    active: prod
  application:
    name: api-passenger

eureka:
 instance:
    hostname: localhost
    instance-id: api-passenger
 client:
    serviceUrl:
        defaultZone: http://root:root@localhost:7900/eureka/



